server:
  port: 6380
spring:
  application:
    name: redis-provider
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  profiles: redis_provider

eureka:
  client:
    service-url:
      defaultZone: http://registry-center:7000/eureka/eureka/
  instance:
    prefer-ip-address: true
nutz:
  dao:
    runtime:
      migration: false